/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autocomplete.textfield;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        AutocompleteTextField classUnderTest = new AutocompleteTextField();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
